### ISSUE TITLE
After installing extension I still get cannot resolve tag for ion-view ETC.

### ISSUE THREAD

**Issue by clintduncan** [madskristensen/IonicPack#1]
Visual studio 2015 enterprise 
Visual studio tools for Apache Cordova update 5
Typescript 1.7.6
ionic pack version 1.0.16 enabled.

**Comment by madskristensen** [comment]
@jmatthiesen can you repro this?

**Comment by clintduncan** [comment]
I have un -installed the extension and re-installed it, but It never seems to pick up the ionic tags. Always have blue squiggles and no intellisense. I suspect some sort of installation, or path issue with either the extension or some of the tooling bits.

**Comment by madskristensen** [comment]
Are you using ReSharper? It messes with HTML IntelliSense. Can you try disable it to see if that helps? I think you can turn off just it's HTML features

**Comment by clintduncan** [comment]
As usual, you nailed it. I have a love hate relationship with re-sharper that just seems to be going further south…..

thanks for the help, sorry to bother you with this.

Clint

Sent from Windows Mail

From: Mads Kristensen
Sent: ‎Tuesday‎, ‎February‎ ‎2‎, ‎2016 ‎9‎:‎08‎ ‎AM
To: madskristensen/IonicPack
Cc: Clint Duncan

Are you using ReSharper? It messes with HTML IntelliSense. Can you try disable it to see if that helps? I think you can turn off just it's HTML features

**Comment by madskristensen** [comment]
Is it possible to turn off just the HTML stuff from ReSharper? If so, can you share a screenshot, so I can put that in the readme file for other users of ReSharper?

**Comment by clintduncan** [comment]
I did not have much luck with turning off just the HTML section. There is not an ON/off, just several screens of settings. suspending Resharper as a whole immediately corrected the ionic tags, but I spent some time checking and unchecking HTML options with no success. I have included a word doc with screen shots incase that is of use to you....For me, it is easy enough to suspend it when working in the cordova project and re-enable if I am in any of the backend projects.
[settings.docx](https://github.com/madskristensen/IonicPack/files/114668/settings.docx)

**Comment by radrad** [comment]
You can choose Custom IntelliSense where all, but HTML Language intellisenses are managed by ReSharper:
![ionicresharpertogether](https://cloud.githubusercontent.com/assets/2520809/19048225/11e95690-896b-11e6-862c-a8a677e0cce4.jpg)
In this case you will have Intellisense warnings for ion-\* tags which are actually Unknown tag(s), but you will have IonicPack intellisense working. You can suppress general category "Unknown tag" in HTML Inspection Severity  by doing:
![resharperunknowntag](https://cloud.githubusercontent.com/assets/2520809/19048640/d7c4cef2-896c-11e6-8721-0efb240b6267.jpg)
In this case you have to be careful and write HTML tags from the offered list since any tags can be written without a warning.

I guess you will have to set "Do not show" for all other warnings like Unknown tag, event etc.
